---
title: Othi's Doll Index
author: |
  | Othi
  | Last Updated: `r format(Sys.time(), '%d %B, %Y')`
output:
    html_document:
        number_sections: false
    pdf_document:
        number_sections: false
geometry: "left=1cm,right=1cm,top=2cm,bottom=2cm"
classoption: landscape
header-includes:
    - \usepackage{datetime}
---

```{r message=F, eval=F, echo=F}
backup packages:
\begin{verbatim}
header-includes:
    - \usepackage{multirow,array,colortbl,graphicx,cellspace,xcoffins,caption,datetime}
    - \usepackage[dvipsnames]{xcolor}
    - \usepackage{xparse}
\end{verbatim}
```

```{r message=FALSE, echo=F, warning=F}
source('dataframes.R', chdir = T)
```

# Doll List
```{r, message=F, echo=F}
condformat(df.dolllist.pretty) %>%
    rule_fill_discrete(Type) %>%
    rule_fill_discrete(Name, expression = df.dolllist$rarity,
                       colours = c("5" = "#FFB600", "4" = "#D6E35A", "3" = "#6BDFCE", "1" = "#DEB6FF")) %>%
    rule_fill_discrete(SLv, expression = df.dolllist$slv,
                       colours = c("10" = "#CBDC2E", "9" = "#DBE770", "8" = "#DBE770",
                                   "7" = "#70DBE7", "6" = "#70DBE7", "5" = "#70DBE7", "4" = "#70DBE7",
                                   "3" = "#E77B70", "2" = "#E77B70", "1" = "#E77B70")) %>%
    rule_fill_discrete(Link, expression = Link == 5, colours = c("TRUE" = "#D6E35A")) %>%
    rule_fill_discrete(Ringed, expression = Ringed == "Yes", colours = c("TRUE" = "#F7AEA5")) %>%
    #rule_fill_gradient(slv) %>%
    theme_htmlTable(rnames = FALSE, n.cgroup = rbind(c(1,2,NA),
                           c(2,2,2)),
                           cspan.rgroup = 2,
                           col.columns = c(rep("none", 1),
                                           rep("#F5FBFF", 2),
                                           rep("none", 1),
                                           rep("#F5FBFF", 3)
                                          ),
                           #css.cgroup =c(rep("padding: 0px 20px 0px;", 2),
                           #              rep("padding: 0px 60px 0px;", 5)),
                           css.cell = "padding: 0px 40px 0px;")
```

## SLv roadmad
```{r message=F, echo=F}
kable(filter.todo.slv, caption="todo", format="markdown")
```

## Link core roadmad
```{r message=F, echo=F}
kable(filter.todo.core, caption="todo", format="markdown")
```

## MOD roadmad
```{r message=F, echo=F}
kable(filter.todo.MOD, caption="todo", format="markdown")
```


# other notes and todo
- team builing concept and needed tables (3x3)
